import { Inter } from 'next/font/google'
import './globals.css'

import { Navigation } from '@/components/navigation'
import type { Metadata } from 'next'
// import Providers from './providers'

import { Inter as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'
import Providers from './providers'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'My WGT Schedule',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <Providers>
          <div className='container mx-auto'>
            <Navigation />
            <div className='px-2'>{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
